version: '3.8'

services:
  # Servidor de Banco de Dados Postgres
  db:
    image: postgres:15
    container_name: smart_time_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: smart_time_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  # API Backend Node.js
  api:
    build: ./server
    container_name: smart_time_api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_NAME: smart_time_db
      PORT: 5000
    ports:
      - "5000:5000"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge